sudo: required
services:
  - docker

before_install:
  - docker build -t sarazahraoui19/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarazahraoui19/docker-react npm run test -- --coverage