sudo: required
services:
  - docker

before_install:
  - docker build -t sarazahraoui19/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarazahraoui19/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: elasticbeanstalk-us-east-2-700426030205
  bucket_path: "react-docker"
  on:
    branch: "master"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"